### ISSUE TITLE
Problem on FreeBSD

### ISSUE THREAD

**Issue by Onepamopa** [medvedv/purifier#10]
Hello,

I've found a problem when running purifier on FreeBSD.
FreeBSD 10.3 64 bit

GCC 5.4.0
DPDK 16.07 from ports, manually edited Makefile to set RTE_TARGET x86_64-native-bsdapp-gcc (default is x86_64-native-bsdapp-clang), and pkg_plist to replace clang with gcc (problem appears on both "gcc" or "clang").
RTE_SDK=/usr/local/share/dpdk
RTE_TARGET=x86_64-native-bsdapp-gcc

Contigmem configured with 2 x 2 GB, top shows 4 GB in use.

Purifier compiles without any errors and runs normally, however here is example of the problem:

1. Purifier start with: -c 0x7 -n 2
2. I configure 2 IPs 10.0.0.2/32 and 10.0.0.3/32 in ACL on port 80 with sec_ctx.
3. I start continuous SYN attack to 10.0.0.2 port 80 (100000 packets per second) and try to open it via browser on another computer.
4. Initially I am able to load http://10.0.0.2:80/, however after 1-2 minutes when I try to load it again - it keeps "loading" without actually displaying anything, then I get connection timeout.
5. At this time if I try to load http://10.0.0.3:80/ - I can load it without any problem but I cannot load http://10.0.0.2:80/
6. If I stop the attack - I can load http://10.0.0.2:80/ immediately, but if I start attack again - after ~1 minute 10.0.0.2 starts to timeout.

This does not happen on Ubuntu, only on FreeBSD.

What could be the problem ?

**Comment by medvedv** [comment]
Hi,

I've tested it in my lab  (FreeBSD 10.3-RELEASE DPDK16.07 x86_64-native-bsdapp-clang)  and I have not seen any problems.
Purifier was started with -c 0x7 -n 2 
>show acl 
        Counter Rule Index      Access list
        89526492        20 src 0.0.0.0/0 dst 10.255.255.10/32 sport_range 0 65535 dport_range 22 22 sec_ctx ololo
Synflood was started towards to 10.255.255.10, victim can see that traffic
...
tcp4       0      0 10.255.255.10.22       182.92.81.22.11456     SYN_RCVD
tcp4       0      0 10.255.255.10.22       131.129.55.63.32284    SYN_RCVD
tcp4       0      0 10.255.255.10.22       7.107.101.87.44682     SYN_RCVD
tcp4       0      0 10.255.255.10.22       153.22.222.104.53716   SYN_RCVD
tcp4       0      0 10.255.255.10.22       217.38.207.88.45438    SYN_RCVD
tcp4       0      0 10.255.255.10.22       45.219.211.81.41866    SYN_RCVD
...
and I can open tcp session from 10.255.255.20
telnet 10.255.255.10 22
Trying 10.255.255.10...
Connected to 10.255.255.10.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.2 FreeBSD-20160310

5 pkts 330 bytes[PRF_TCP_STATE_ESTABL] Src ip 10.255.255.20 Dst ip 10.255.255.10 Src port 43325 Dst port 22 TTL 1797

Try to dump traffic before and after purifier.

**Comment by medvedv** [comment]
Is there any news?

**Comment by Onepamopa** [comment]
It was a local problem.
