### ISSUE TITLE
Centos 6

### ISSUE THREAD

**Issue by mountdevhands** [medvedv/purifier#2]
Здравствуйте!

Данное решение можно устанавливать на ядра 2.6.32 для Centos 6?

**Comment by Louvremaster** [comment]
Плюс вот еще собираю для Debian-8. Получаю следующее:
#:/usr/src/purifier/src# export RTE_SDK=/usr/src/purifier/dpdk-1.7.1
#:/usr/src/purifier/src# export RTE_TARGET=x86_64-native-linuxapp-gcc
#:/usr/src/purifier/src# make
/usr/src/purifier/dpdk-1.7.1/mk/rte.extvars.mk:71: /usr/src/purifier/dpdk-1.7.1/x86_64-native-linuxapp-gcc/.config: No such file or directory
/usr/src/purifier/dpdk-1.7.1/mk/rte.vars.mk:99: *** RTE_ARCH is not defined.  Stop.

Что может быть?

**Comment by mountdevhands** [comment]
Плюс в целом, поясните, пожалуйста работу приложения. Пример, Debian-8, у меня скажем, есть интерфейс eth2, с драйвером igb:

# Network devices using kernel driver

0000:02:00.0 'I350 Gigabit Network Connection' if=eth2 drv=igb unused=igb_uio _Active_

Я скажем, его переключу в igb_uio, вся ведь настройка сети для данного интерфейса пропадает. Плюс purifier почему-то отказывается запускаться:
:/usr/src/purifier/src/build/app# ./purifier -c 0x7 -n 4
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 2 on socket 0
EAL: Detected lcore 3 as core 3 on socket 0
EAL: Detected lcore 4 as core 0 on socket 0
EAL: Detected lcore 5 as core 1 on socket 0
EAL: Detected lcore 6 as core 2 on socket 0
EAL: Detected lcore 7 as core 3 on socket 0
EAL: Support maximum 64 logical core(s) by configuration.
EAL: Detected 8 lcore(s)
EAL: Setting up memory...
EAL: Ask a virtual area of 0x1000000 bytes
EAL: Virtual area found at 0x7fb303e00000 (size = 0x1000000)
EAL: Ask a virtual area of 0xd400000 bytes
EAL: Virtual area found at 0x7fb2f6800000 (size = 0xd400000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7fb2f6400000 (size = 0x200000)
EAL: Ask a virtual area of 0x71800000 bytes
EAL: Virtual area found at 0x7fb284a00000 (size = 0x71800000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7fb284600000 (size = 0x200000)
EAL: Requesting 1024 pages of size 2MB from socket 0
EAL: TSC frequency is ~3600000 KHz
EAL: Master core 0 is ready (tid=774a840)
EAL: Core 2 is ready (tid=83dfe700)
EAL: Core 1 is ready (tid=845ff700)
EAL: PCI device 0000:02:00.0 on NUMA socket -1
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL:   0000:02:00.0 not managed by VFIO driver, skipping
EAL:   PCI memory mapped at 0x7fb307614000
EAL:   PCI memory mapped at 0x7fb307751000
EAL: PCI device 0000:02:00.1 on NUMA socket -1
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL:   0000:02:00.1 not managed by VFIO driver, skipping
EAL:   PCI memory mapped at 0x7fb305d26000
EAL:   PCI memory mapped at 0x7fb307610000
Init TCP_Hash on core 2
PMD: To improve 1G driver performance, consider setting the TX WTHRESH value to 4, 8, or 16.
PMD: To improve 1G driver performance, consider setting the TX WTHRESH value to 4, 8, or 16.
EAL: Error - exiting with code: 1
  Cause: rte_eth_dev_add_5tuple_filter: err=-38

Что я делаю не так и как сделать чтобы сеть собственно с драйвером igb_uio работала, чтобы можно было направить пакеты?

**Comment by medvedv** [comment]
День добрый!

Если на вашем ядре собрался DPDK, то и purifier должен работать. Что касается конкретно вашего ядра, то необходимо наложить ряд патчей, подробности 
http://dpdk.org/doc/guides-2.1/linux_gsg/sys_reqs.html и
http://dpdk.org/doc/guides-2.0/rel_notes/faq.html#does-my-kernel-require-patching-to-run-the-dpdk
По второму вопросу, а что за чип сетевой карты? Скорее всего чип не поддерживает установку five tuple filter.
