### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Onepamopa** [medvedv/purifier#4]
Hello,

How do you config this ? Is there a config file or something ?

**Comment by Onepamopa** [comment]
Also:
./purifier -c 0x7 -n 4
EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:01:00.0 on NUMA socket -1
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL: PCI device 0000:01:00.1 on NUMA socket -1
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL: Error - exiting with code: 1
  Cause: TCP_hash_create on core 2 failed

**Comment by medvedv** [comment]
Hi,

Currently it is configurable via the command line.
I have plans to implement config files in future.
