### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by babay-re** [medvedv/purifier#5]
Hi.
Can not compile on Ubuntu 16.04.1

  CC main.o
  CC prf_stateful.o
In file included from /root/src/purifier/src/prf_stateful.c:47:0:
/root/src/purifier/src/prf_sec_ctx_api.h:50:12: warning: inline function ‘prf_synproxy_cookie_check’ declared but never defined
 inline int prf_synproxy_cookie_check(struct ipv4_hdr *iph, struct tcp_hdr *th, uint32_t time_min, struct prf_tcpopts *options);
            ^
  CC prf_sec_ctx.o
In file included from /root/src/purifier/src/prf_sec_ctx.c:46:0:
/root/src/purifier/src/prf_sec_ctx.c:116:53: warning: ‘prf_msstab’ is static but used in inline function ‘prf_synproxy_cookie_check’ which is not static
   options->mss =  prf_msstab[data & (PRF_ARRAY_SIZE(prf_msstab) - 1)];
                                                     ^
/root/src/purifier/src/main.h:45:45: note: in definition of macro ‘PRF_ARRAY_SIZE’
 #define PRF_ARRAY_SIZE(x) (sizeof(x)/sizeof(x[0]))
                                             ^
/root/src/purifier/src/prf_sec_ctx.c:116:53: warning: ‘prf_msstab’ is static but used in inline function ‘prf_synproxy_cookie_check’ which is not static
   options->mss =  prf_msstab[data & (PRF_ARRAY_SIZE(prf_msstab) - 1)];
                                                     ^
/root/src/purifier/src/main.h:45:35: note: in definition of macro ‘PRF_ARRAY_SIZE’
 #define PRF_ARRAY_SIZE(x) (sizeof(x)/sizeof(x[0]))
                                   ^
/root/src/purifier/src/prf_sec_ctx.c:116:19: warning: ‘prf_msstab’ is static but used in inline function ‘prf_synproxy_cookie_check’ which is not static
   options->mss =  prf_msstab[data & (PRF_ARRAY_SIZE(prf_msstab) - 1)];
                   ^
In file included from /root/src/dpdk-16.07/x86_64-native-linuxapp-gcc/include/rte_jhash.h:52:0,
                 from /root/src/purifier/src/prf_sec_ctx.c:35:
/root/src/dpdk-16.07/x86_64-native-linuxapp-gcc/include/rte_byteorder.h:83:8: warning: ‘rte_arch_bswap32’ is static but used in inline function ‘prf_synproxy
_cookie_check’ which is not static
        rte_arch_bswap32(x)))
/root/src/dpdk-16.07/x86_64-native-linuxapp-gcc/include/rte_byteorder.h:112:29: note: in expansion of macro ‘rte_bswap32’
 #define rte_be_to_cpu_32(x) rte_bswap32(x)
                             ^
/root/src/purifier/src/prf_sec_ctx.c:110:17: note: in expansion of macro ‘rte_be_to_cpu_32’
  uint32_t seq = rte_be_to_cpu_32(th->sent_seq) - 1;
                 ^
/root/src/dpdk-16.07/x86_64-native-linuxapp-gcc/include/rte_byteorder.h:82:8: warning: ‘rte_constant_bswap32’ is static but used in inline function ‘prf_synproxy_cookie_check’ which is not static
        rte_constant_bswap32(x) :  \
        ^
/root/src/dpdk-16.07/x86_64-native-linuxapp-gcc/include/rte_byteorder.h:112:29: note: in expansion of macro ‘rte_bswap32’
 #define rte_be_to_cpu_32(x) rte_bswap32(x)
                             ^
/root/src/purifier/src/prf_sec_ctx.c:110:17: note: in expansion of macro ‘rte_be_to_cpu_32’
  uint32_t seq = rte_be_to_cpu_32(th->sent_seq) - 1;
                 ^
/root/src/dpdk-16.07/x86_64-native-linuxapp-gcc/include/rte_byteorder.h:83:8: warning: ‘rte_arch_bswap32’ is static but used in inline function ‘prf_synproxy_cookie_check’ which is not static
        rte_arch_bswap32(x)))
        ^
/root/src/dpdk-16.07/x86_64-native-linuxapp-gcc/include/rte_byteorder.h:112:29: note: in expansion of macro ‘rte_bswap32’
 #define rte_be_to_cpu_32(x) rte_bswap32(x)
                             ^
/root/src/purifier/src/prf_sec_ctx.c:109:20: note: in expansion of macro ‘rte_be_to_cpu_32’
  uint32_t cookie = rte_be_to_cpu_32(th->recv_ack) - 1;
                    ^
/root/src/dpdk-16.07/x86_64-native-linuxapp-gcc/include/rte_byteorder.h:82:8: warning: ‘rte_constant_bswap32’ is static but used in inline function ‘prf_synproxy_cookie_check’ which is not static
        rte_constant_bswap32(x) :  \
        ^
/root/src/dpdk-16.07/x86_64-native-linuxapp-gcc/include/rte_byteorder.h:112:29: note: in expansion of macro ‘rte_bswap32’
 #define rte_be_to_cpu_32(x) rte_bswap32(x)
                             ^
/root/src/purifier/src/prf_sec_ctx.c:109:20: note: in expansion of macro ‘rte_be_to_cpu_32’
  uint32_t cookie = rte_be_to_cpu_32(th->recv_ack) - 1;

CC prf_acl.o
In file included from /root/src/purifier/src/prf_acl.c:42:0:
/root/src/purifier/src/prf_sec_ctx_api.h:50:12: warning: inline function ‘prf_synproxy_cookie_check’ declared but never defined
 inline int prf_synproxy_cookie_check(struct ipv4_hdr *iph, struct tcp_hdr *th, uint32_t time_min, struct prf_tcpopts *options);
            ^
  CC prf_cmdline.o
  LD purifier

prf_acl.o: In function `prf_acl_accept':
prf_acl.c:(.text+0x11c7): undefined reference to `prf_synproxy_cookie_check'
prf_acl.o: In function `prf_acl_sec_ctx':
prf_acl.c:(.text+0x298a): undefined reference to `prf_synproxy_cookie_check'
collect2: error: ld returned 1 exit status
/root/src/dpdk-16.07/mk/rte.app.mk:231: recipe for target 'purifier' failed
make[1]: *** [purifier] Error 1
/root/src/dpdk-16.07/mk/rte.extapp.mk:42: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by medvedv** [comment]
Fixed, check check the last commit. The problem was caused because of GCC5 different semantics foe inline functions 
https://gcc.gnu.org/gcc-5/porting_to.html

**Comment by babay-re** [comment]
Hi.
It's compiled, thanks.

But now I have

./purifier -c 0x7 -n 4
EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:01:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL: PCI device 0000:01:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL: Error - exiting with code: 1
Cause: TCP_hash_create on core 2 failed

What I do wrong?

**Comment by medvedv** [comment]
You haven't enough memory. You need al least 1.5Gb of memory per worker lcore.
In your case it's looks like you haven't any hugepages:
EAL: No free hugepages reported in hugepages-1048576kB
Check /proc/meminfo
and
/sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages

**Comment by babay-re** [comment]
Thanks for help
