### ISSUE TITLE
Compatible NICs ?

### ISSUE THREAD

**Issue by Onepamopa** [medvedv/purifier#6]
What NICs are compatible with purifier ?
What exactly is needed in order to run it without errors ?

I tested with Intel I350 but purifier spit errors (I posted them in another post)

**Comment by medvedv** [comment]
In general purifier should be compatible with i350 (82580 chip). Moreover, it is compatible with all NICs that support Ethertype and Ntuple filters.
Currently purifier was tested with ixgbe only, but I have plans to test it with broadcom/i40 in the nearest future.
