### ISSUE TITLE
FreeBSD contigmem

### ISSUE THREAD

**Issue by Onepamopa** [medvedv/purifier#9]
Hello,

I'm trying to run purifier on FreeBSD 10.3.
DPDK 16.07 module loaded, there is no "hugepages" in freebsd, there is something called contigmem.
What values do I set for purifier to work ?
Tried with:
hw.contigmem.num_buffers=1 (and 2)
hw.contigmem.buffer_size=1073741824

Result:

EAL: Detected 4 lcore(s)
EAL: Contigmem driver has 1 buffers, each of size 1GB
EAL: Mapped memory segment 1 @ 0x802400000: physaddr:0x140000000, len 1073741824
EAL: PCI scan found 19 devices
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10c9 rte_igb_pmd
EAL: PCI device 0000:01:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10c9 rte_igb_pmd
EAL: Error - exiting with code: 1
  Cause: TCP_hash_create on core 2 failed

**Comment by medvedv** [comment]
There is not enough memory. Purifier needs at leas 1.5Gb per worker lcore (%total_number_of_cores_provided_by_-c_option% - 2).
Or you can decrease state stable by decreasing PRF_TCP_CONN_HASH_SIZE defined in prf_stateful.h
